apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mina-ingress
spec:
  ingressClassName: cilium
  rules:
  - host: www.example.com
    http:
      paths:
      # Backend Routes
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3000
      - path: /items
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3000
      - path: /messages
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3000
      # Frontend Route (Catch-all)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
