apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storageClass.yml
  - secrets.yaml
  - configmap.yaml
  - mysql-pvc.yaml
  - mysql-service.yaml
  - mysql-deployment.yaml
  - redis-service.yaml
  - redis-deployment.yaml
  - backend-service.yaml
  - backend-deployment.yaml
  - frontend-service.yaml
  - frontend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - backend-hpa.yaml
  - frontend-hpa.yaml

