apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny
  namespace: project-mina
spec:
  endpointSelector: {}
  ingress:
  - {} # Deny all ingress (empty rule but no 'from' means deny)
  egress:
  - {} # Deny all egress
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-dns-egress
  namespace: project-mina
spec:
  endpointSelector: {}
  egress:
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        "k8s:k8s-app": kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
      - port: "53"
        protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: frontend-policy
  namespace: project-mina
spec:
  endpointSelector:
    matchLabels:
      app: frontend
  ingress:
  - fromEntities:
    - world
    - cluster
  egress:
  - toEndpoints:
    - matchLabels:
        app: backend
        "k8s:io.kubernetes.pod.namespace": project-mina
    toPorts:
    - ports:
      - port: "3000"
        protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: backend-policy
  namespace: project-mina
spec:
  endpointSelector:
    matchLabels:
      app: backend
  ingress:
  - fromEntities:
    - world
    - cluster
  - fromEndpoints:
    - matchLabels:
        app: frontend
        "k8s:io.kubernetes.pod.namespace": project-mina
    toPorts:
    - ports:
      - port: "3000"
        protocol: TCP
  egress:
  - toEndpoints:
    - matchLabels:
        app: mysql
        "k8s:io.kubernetes.pod.namespace": project-mina
    toPorts:
    - ports:
      - port: "3306"
        protocol: TCP
  - toEndpoints:
    - matchLabels:
        app: redis
        "k8s:io.kubernetes.pod.namespace": project-mina
    toPorts:
    - ports:
      - port: "6379"
        protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: redis-policy
  namespace: project-mina
spec:
  endpointSelector:
    matchLabels:
      app: redis
  ingress:
  - fromEndpoints:
    - matchLabels:
        app: backend
        "k8s:io.kubernetes.pod.namespace": project-mina
    toPorts:
    - ports:
      - port: "6379"
        protocol: TCP
  egress:
  - toEndpoints:
    - matchLabels:
        app: mysql
        "k8s:io.kubernetes.pod.namespace": project-mina
    toPorts:
    - ports:
      - port: "3306"
        protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: mysql-policy
  namespace: project-mina
spec:
  endpointSelector:
    matchLabels:
      app: mysql
  ingress:
  - fromEndpoints:
    - matchLabels:
        app: backend
        "k8s:io.kubernetes.pod.namespace": project-mina
    - matchLabels:
        app: redis
        "k8s:io.kubernetes.pod.namespace": project-mina
    toPorts:
    - ports:
      - port: "3306"
        protocol: TCP
