apiVersion: v1
kind: Secret
metadata:
  name: mina-secrets
type: Opaque
data:
  # echo -n 'password' | base64
  # Values as placeholders
  mysql-root-password: cm9vdA==       # root
  mysql-password: cGFzc3dvcmQ=        # password
  jwt-secret: cGFzc3dvcmQxMjM=        # password123
