apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mina-storage
  annotations:
    # This makes it the default so you don't always have to specify the name in PVCs
    storageclass.kubernetes.io/is-default-class: "true" 
provisioner: cinder.csi.openstack.org
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer # Recommended for multi-AZ clusters
parameters:
  # This must match a 'Volume Type' in your OpenStack (e.g. "ssd" or "__DEFAULT__")
  type: "default"
